import Foundation

/// Constants shared by the app (client) and the CrossbarHelper daemon (server).
/// Compiled into both targets: the Mach service name and the code-signing
/// requirements must match on both ends or the connection can't form.
enum HelperConstants {
    /// The privileged helper's Mach service name (matches its launchd plist).
    static let machServiceName = "com.breed.Crossbar.helper"

    /// The helper's bundle identifier, embedded in its binary's Info.plist.
    static let helperBundleID = "com.breed.Crossbar.helper"

    /// The launchd plist inside `Contents/Library/LaunchDaemons`.
    static let plistName = "com.breed.Crossbar.helper.plist"

    static let appBundleID = "com.breed.Crossbar"

    /// Developer ID team that signs both ends.
    static let teamID = "YA83Q8FTH3"

    /// Requirement the helper enforces on every client: the Crossbar app, signed by
    /// our team. The OS checks it per message, before helper code runs.
    static let clientRequirement =
        "identifier \"\(appBundleID)\" and anchor apple generic and " +
        "certificate leaf[subject.OU] = \"\(teamID)\""

    /// Requirement the app enforces on the helper. SMAppService already guarantees
    /// provenance; pinning costs nothing.
    static let helperRequirement =
        "identifier \"\(helperBundleID)\" and anchor apple generic and " +
        "certificate leaf[subject.OU] = \"\(teamID)\""

    /// XPC message keys.
    enum Key {
        static let op = "op"                 // string (request)
        static let serviceID = "serviceID"   // string (request): the target SCNetworkService ID
        static let enabled = "enabled"       // bool (request)
        static let ok = "ok"                 // bool (reply)
        static let error = "error"           // string (reply, on failure)
    }

    /// The helper's only operation: enable or disable one existing service.
    static let opSetEnabled = "setEnabled"

    /// Service IDs are generated by SystemConfiguration as UUID strings. Anything
    /// else (control characters, newlines, oversized input) is refused before the
    /// helper touches preferences or writes the audit log, so a crafted ID can't
    /// forge a log line. Switchback hit exactly that with a newline in an ID.
    static func isWellFormedServiceID(_ id: String) -> Bool {
        !id.isEmpty && id.utf8.count <= 64 && id.unicodeScalars.allSatisfy {
            ("A"..."Z").contains($0) || ("a"..."z").contains($0) || ("0"..."9").contains($0) || $0 == "-"
        }
    }

    /// Reply error codes. The contract only grows; clients treat unknown codes as
    /// failures.
    enum ErrorCode {
        static let unknownOp = "unsupported-op"
        static let missingServiceID = "missing-service-id"
        static let unknownServiceID = "unknown-service-id"
        static let openPrefsFailed = "open-prefs-failed"
        static let setEnabledFailed = "set-enabled-failed"
        static let commitFailed = "commit-failed"
        static let applyFailed = "apply-failed"
    }
}
